version: '3'
services:
  os161:
    image: marcopalena/polito-os161:latest
    command:
      - /bin/bash
    volumes:
      - polito-os161-vol:/home/os161user
#  filebrowser:
#    image: filebrowser/filebrowser
#    volumes:
#      - polito-os161-vol:/srv
#    ports:
#      - "8079:80"
  html:
    image: httpd:2.4
    ports:
      - "8078:80"
    volumes:
      - polito-os161-vol:/usr/local/apache2/htdocs/

volumes:
    polito-os161-vol:
        external: false
